title: Notepad Tab
tagline: A simple, secure and private note taking tool
description: Write down anything and have it automatically persisted in the address bar and in the browser's history. Easily back up or share any note by simply copy and pasting the URL.
url: https://notepadtab.com

# Disabled due to https://github.com/rubygems/rubygems/issues/7652
# theme: minima
# Added due to https://github.com/rubygems/rubygems/issues/7652
remote_theme: jekyll/minima
plugins:
    - jekyll-node-module
    # Added due to https://github.com/rubygems/rubygems/issues/7652
    - jekyll-remote-theme
exclude:
    - LICENSE.md
    - package-lock.json
    - package.json
    - README.md
defaults:
    - scope:
          path: ""
      values:
          image: /assets/images/favicon/android-chrome-512x512.png

minima:
    skin: auto
    date_format: "%F"
    social_links:
        - platform: github
          user_url: https://github.com/revolter/notepadtab.com
node_modules:
    assets:
        js: assets/js
sass:
    style: compressed
    sourcemap: development
